name: Close Previous Issue

on:
  issues:
    types: [opened]

jobs:
  closePreviousIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close Previous Issue
        run: |
          # 获取当前仓库的所有已关闭的 issue
          closed_issues=$(curl -s -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=closed" | jq -r '.[].number')

          # 获取最新创建的 issue
          newest_issue=$(curl -s -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq -r '.[0].number')

          # 关闭上一个 issue
          for issue in $closed_issues; do
            if [[ $issue -ne $newest_issue ]]; then
              echo "$issue"
              curl -X PATCH -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d '{"state": "closed"}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue"
              break
            fi
          done