name: Close Previous Issues

on:
  issues:
    types: [opened]

jobs:
  closePreviousIssues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close Previous Issues
        run: |
          # 获取当前仓库的所有打开的 issue
          open_issues=$(curl -s -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq -r '.[].number')

          # 获取最新创建的 issue
          newest_issue=$(curl -s -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | jq -r '.[0].number')

          # 关闭之前的打开的 issue
          for issue in $open_issues; do
            if [[ $issue -ne $newest_issue ]]; then
              # 添加评论
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/issues/$issue/comments \
                -d '{"body":"Good to hear"}'
              # 添加关闭issue
              curl -X PATCH -H "Authorization: Bearer ${{ secrets.iOS_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d '{"state": "closed"}' \
                "https://api.github.com/repos/${{ github.repository }}/issues/$issue"

            fi
          done